name: Test

on: [push]

jobs:
  test:
    runs-on: macos-latest # Use macos for iOS simulator support

    steps:
      - uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2  # Updated to v2
        with:
          channel: 'stable'

      - name: Start iOS Simulator # Add this step for iOS
        uses: futureware-tech/simulator-action@v1  # Install & Start simulator
        with:
          model: 'iPhone 15 Pro Max' # Choose your dswesired simulator model

      - name: Build app
        run:  flutter run -d "iPhone 15 Pro Max" --debug & 
              FLUTTER_PID=$! 
              sleep 300 
              pkill -P $FLUTTER_PID


      - name: Install Dependencies (Maestro, IDB Companion)
        run: |
          curl -Ls "https://get.maestro.mobile.dev" | bash
          brew tap facebook/fb
          brew install facebook/fb/idb-companion

      - name: Run Maestro Test
        run: maestro test test.yml  # Use the full path to filename.yml
        env:
          FLUTTER_VERSION: stable